# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: mail.telalca.com
    port: 26
    domain: telalca.com
    authentication: :login
    user_name: arnaud.coquelet@telalca.com
    password: arnaud
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: 127.0.0.1
    port: 25
    domain: example.net
    authentication: :login
    user_name: redmine@example.net
    password: redmine
